apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test3
 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: jiajiac/go-web-hello-world
        



       
          



